### ISSUE TITLE
Install Script

### ISSUE THREAD

**Issue by benaubin** [rootly-io/cli#4]
It might be worth creating an install script that can be hosted to make one-line installs possible on non-Mac platforms. The Deno one seems pretty simple, MIT licensed and easily customized (used over at fly.io).

See https://deno.land/x/install@v0.1.4/install.sh

Then, installing on non-homebrew platforms is just:

```
curl -L https://rootly.io/install.sh | sh
```

**Comment by Matt-Gleich** [comment]
ohh this would be cool. @kwent what do you think?

**Comment by kwent** [comment]
@benaubin Awesome idea. @Matt-Gleich Wanna give a shot at it?

**Comment by Matt-Gleich** [comment]
Sure! I have some school work I have to do today but I can get started on it tonight.
